/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : SPI COMMUNICATION WITH ARDUINO BOARD USING SPI
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 *
 *
 *- --- --- --- --- --- --ABOUT THE PROJECT  --- --- --- --- ---
 *  SPI MASTER (STM) and SPI SLAVE (ARDUINO)
 *  when the button on the master is pressed , master should send string of data to
 *  Arduino slave connected/ the data received by arduinow will be displayed on arduino
 *  Serial port.
 *  1. use SPI full duplex mode
 *  2. st board will be in SPI master mode and arduino will be configured for SOI slave
 *  3. use dff =0
 *  4. use SSM =0;
 *  SCLK = 2Mhx , fclk 16 Mhz
 *
 *
 *    ----------------------------- IMPORTANT NOTE --------------------------
 *     there is voltage differnce between the Stm32 board and the arduino board.
 *     arduino operate at 5v and Stm32 board operate at 3v
 *     so we need logic shifter to perform this exercise.
 *
 *     if logic shifter is not in there then , make sure the stm32 is powered on before
 *     making such connection.
 *
 *    -------------------------config arduino -----------------------------
 *   go to arduino sketch, download  - 001SPISlaveRxstring.ino
 *
 *
 ******************************************************************************
 */

#include <string.h>
#include "stm32f407xx.h"
#include "stm32f407_driver.h"
#include "stm32f407_spi_driver.h"
// writing code for the SPI protocol validation .
// no slave is needed for the verifiying the code

/* for SPI2
 *  NSS  -> PB12
 *  SCK  -> PB13
 *  MISO -> PB14
 *  MOSI -> PB15
 *  ALT MODE -> 5
 */
void SPI_GPIOInits(void){
	GPIO_Handle_t SPIPins;
	SPIPins.pGPIOx = GPIOB;
	SPIPins.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	SPIPins.GPIO_PinConfig.GPIO_PinAltFunMode = 5;
	SPIPins.GPIO_PinConfig.GPIO_OPType = GPIO_OP_TYPE_PP;
	SPIPins.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	SPIPins.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;

	// set the SCLK
	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	GPIO_Init(&SPIPins);

	// MOSI
	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
	GPIO_Init(&SPIPins);

	//MISO
	//SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;
	//GPIO_Init(&SPIPins);

	//NSS
	SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	GPIO_Init(&SPIPins);

}

void SPI2_Inits(void){
	SPI_Handle_t SPIHandle2;

	SPIHandle2.pSPIx = SPI2;
	SPIHandle2.SPIConfig.SPI_BusConfig = SPI_BUS_CONFIG_FD;
	SPIHandle2.SPIConfig.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER;
	SPIHandle2.SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV_BY_8; // 2mhz
	SPIHandle2.SPIConfig.SPI_DFF = SPI_DFF_8_BIT;
	SPIHandle2.SPIConfig.SPI_CPHA = SPI_CPOL_LOW;
	SPIHandle2.SPIConfig.SPI_CPOL = SPI_CPHA_LOW;
	SPIHandle2.SPIConfig.SPI_SSM = SPI_SSM_DI; //for NSS - hardware slave management

	SPI_Init(&SPIHandle2);

}

void GPIO_ButtonInit(void){
	// for the button
	GPIO_Handle_t GpioButton;
	GpioButton.pGPIOx = GPIOA;
	GpioButton.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
	GpioButton.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
	GpioButton.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GpioButton.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	//GPIO_PeriClockControl(GPIOA,ENABLE); no need to do bcs we have do this in init
	GPIO_Init(&GPIOButton);
}
void Delay(void){
	for (uint32_t i =0; i<500000/2;i++);
}
int main(void){
char user_data[] = "hello World";
	SPI_GPIOInits(); // initialize the GPIO pin to behave the SPI2 pins

	SPI2_Inits(); //initialize the SPI2 peripheral parameters
/*
 *  making SSOE 1 does NSS output enable
 *  THE NSS Pin is automatically managed by hardware
 *  ie when SPE= 1 , NSS will be pulled to low
 *  and NSS pin will be high when SPE = 0
 */
	GPIO_ButtonInit();
	SSI_SSOEConfig(SPI2,ENABLE);
	while(1){
		while(! GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_0));
		Delay();

		// this makes NSS signal internally high and avoid MODF error
		SSI_PeripheralControl(SPI2,ENABLE); // enable the SSI bit

		SPI_SendData(SPI2,(uint8_t*) user_data, strlen(user_data));
		SSI_PeripheralControl(SPI2,DISABLE); // don't forget to do that
// not yet complete after 2:50

	}


	return 0;
}
