/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int main(void)
{	// for the led
	uint32_t* pClkCtrlReg = (uint32_t*) 0x40023830;
	uint32_t* pPortDModeReg = (uint32_t*) 0x40020C00;
	uint32_t* pPortDOutReg = (uint32_t*) 0x40020C14;
	*pClkCtrlReg |= (1<<3); // set d port
	*pPortDModeReg &= ~(3<<24); // reset the mode
	*pPortDModeReg |= (1<<24); // set the mode 01


	// for input form the A port
	// no need to do it twice just set the uint32_t* pClkCtrlReg2 = (uint32_t*) 0x40023830;
	*pClkCtrlReg |= (1<<0);

	uint32_t* pPortAModeReg2 = (uint32_t*)0x40020000; // 0x4002 0000+ 0x00
	*pPortAModeReg2 &= ~(3<<0);

	uint32_t* pPortAInReg2 = (uint32_t*)0x40020010; //0x40020000 + 0x10


	uint32_t* pinStatus  =(uint32_t)*pPortAInReg2 & 0x01; //using the last pin
	while (1){
		if (pinStatus ){
			// turn on
			*pPortDOutReg |= (1<<12);
		}
		else{
			*pPortDOutReg &= ~(1<<12);
		}
	}
}
