/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
	RCC_AHB1_ENR_t volatile *const pClkCtrlReg = (RCC_AHB1_ENR_t*)0x40023830;  //  0x4002 3800 + 0x30
	GPIOx_MODE_t volatile *const pGpioMode = (GPIOx_MODE_t*)0x40020C00;  //  0x4002 0C00+0x00
	GPIOx_ODR_t volatile *const pGpioOutReg = (GPIOx_ODR_t*)0x40020C14;  //  0x4002 0C00 + 0x14
void led(void);
void extLed(void);
// software delay
void sDelay(){
	for (uint32_t i = 0; i<300000;i++);
}

int main(void)
{
	pClkCtrlReg->gpio_d_en =1;  // gpio d enable
	pClkCtrlReg ->gpio_a_en =1; // enabling A gpio
	pGpioMode ->pin_12 =1; //setting the mode of the gpio pin 12
	pGpioMode ->pin_13 =1;
	pGpioMode ->pin_14 = 1;
	pGpioMode ->pin_15 =1;
	pGpioMode -> pin_1 =1;
	pGpioMode -> pin_2 =1;
	pGpioMode -> pin_3 =1;
	pGpioMode ->pin_4 =1;
	pGpioMode -> pin_5 =1;
	pGpioMode -> pin_6 = 1;

	//pGpioOutReg->pin_12 =1; // Setting the state of the gpio pin12
	while (1){led();
	extLed();
	}

return 0;
}
void extLed(void){
	pGpioOutReg ->pin_1 = 1;sDelay();
	pGpioOutReg ->pin_2 = 1;sDelay();
	pGpioOutReg ->pin_3 = 1;sDelay();
	pGpioOutReg ->pin_4 = 1;sDelay();
	pGpioOutReg ->pin_5 = 1;sDelay();
	pGpioOutReg ->pin_6 = 1;sDelay();
	sDelay();
	pGpioOutReg ->pin_1 = 0;sDelay();
	pGpioOutReg ->pin_2 = 0;sDelay();
	pGpioOutReg ->pin_3 = 0;sDelay();
	pGpioOutReg ->pin_4 = 0;sDelay();
	pGpioOutReg ->pin_5 = 0;sDelay();
	pGpioOutReg ->pin_6 = 0;sDelay();
}
void led(void){
	pGpioOutReg ->pin_12 = 1;
	sDelay();
	pGpioOutReg ->pin_12 = 0;sDelay();
	pGpioOutReg ->pin_13 = 1;sDelay();
	pGpioOutReg ->pin_13 = 0;sDelay();
	pGpioOutReg ->pin_14 = 1;sDelay();
	pGpioOutReg ->pin_14 = 0;sDelay();
	pGpioOutReg ->pin_15 = 1;sDelay();
	pGpioOutReg ->pin_15 = 0;sDelay();

}
