/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int main(void)
{
    uint32_t *pClkCtrlReg = (uint32_t*)0x40023830;
    uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
    uint32_t *pPortDOutReg = (uint32_t*)0x40020C14;

    // enable the clock gpio
    *pClkCtrlReg |= 0x08;

    // configure the mode of the io pins as ouptut
    //clear the 24 and 25th bit position clear
    *pPortDModeReg &= 0xFCFFFFFF;
    //make 24th bit reg as 1 or set
    *pPortDModeReg |= 0x01000000;
    //set 12thbit of data register to high
    *pPortDOutReg |= 0x1000;
    while(1); // infinity loop

    return 0;

}
