/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include <stdio.h>
void sDelay(void);
int main(void)
{
	uint32_t volatile *const pGpioDModeReg = (uint32_t*)(0x40020C00);
	uint32_t volatile *const pInputDataReg = (uint32_t*)(0x40020C00+0x10) ;
	uint32_t volatile *const pOutputDataReg = (uint32_t*)(0x40020C00+0x14);
	uint32_t volatile *const pClkCtrlReg = (uint32_t*) (0x40023800+0x30);
	uint32_t volatile *const pPullupDownReg = (uint32_t*)(0x40020C00+0x0C) ;

	// enable the peripheral clk
	*pClkCtrlReg |= (1<<3);

	//config rows pd0,pd1to pd3 as output -rows
	*pGpioDModeReg &= ~(0xFF);
	*pGpioDModeReg |= (0x55);  // only in case of output this can be done
	// config columns pd8 to pd11
	*pGpioDModeReg &= ~(0xFF<<16);
// may be it is removed	*pGpioDModeReg |= (0x55<<16);	// not in case of input

	// emable the internal pull up register
	*pPullupDownReg &= ~(0xFF << 16);
	*pPullupDownReg |= (0x55<<16);

////////////////////////////////////////////////////////////////////////////////////////

while(1){
	// make all rows high
	*pOutputDataReg |= 0x0F;

	// make r1 Low (pd0)
	*pOutputDataReg &= ~(1<<0);

	//scan the column
	// check for the c1 PB8 low or high
	if(!(*pInputDataReg & (1<<8))){
		printf("key is pressed : 1 \n");
	}
	sDelay();
	if(!(*pInputDataReg & (1<<9))){
		printf("key is pressed : 2 \n");
	}
	sDelay();
	if(!(*pInputDataReg & (1<<10))){
		printf("key is pressed : 3 \n ");
	}
	sDelay();
	if(!(*pInputDataReg & (1<<11))){
		printf("key is pressed : A \n");
	}
	sDelay();

//////////////////////////////////////////////////////////////////////////////////////

	/////////////////////////////////////////////////////////////////////////////
	// make all rows high
	*pOutputDataReg |= 0x0F;

	// make r2 Low (pd1)
	*pOutputDataReg &= ~(1<<1);
	//scan the column
	// check for the c1 PB8 low or high
	if(!(*pInputDataReg & (1<<8))){
		printf("key is pressed : 4\n");
	}
	sDelay();
	if(!(*pInputDataReg & (1<<9))){
		printf("key is pressed : 5 \n");
	}
	sDelay();
	if(!(*pInputDataReg & (1<<10))){
		printf("key is pressed : 6 \n ");
	}
	sDelay();
	if(!(*pInputDataReg & (1<<11))){
		printf("key is pressed : B \n");
	}
	sDelay();

/////////////////////////////////////////////////////////////////
	/////////////////////////////////////////////////////

	// make all rows high
	*pOutputDataReg |= 0x0F;

	// make r3 Low (pd2)
	*pOutputDataReg &= ~(1<<2);
	//scan the column
	// check for the c1 PB8 low or high
	if(!(*pInputDataReg & (1<<8))){
		printf("key is pressed : 7\n");
	}
	sDelay();
	if(!(*pInputDataReg & (1<<9))){
		printf("key is pressed : 8 \n");
	}
	sDelay();
	if(!(*pInputDataReg & (1<<10))){
		printf("key is pressed : 9 \n ");
	}
	sDelay();
	if(!(*pInputDataReg & (1<<11))){
		printf("key is pressed : C \n");
	}
	sDelay();

////////////////////////////////////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////////////////////////
	// make all rows high
	*pOutputDataReg |= 0x0F;

	// make r4 Low (pd3)
	*pOutputDataReg &= ~(1<<3);
	//scan the column
	// check for the c1 PB8 low or high
	if(!(*pInputDataReg & (1<<8))){
		printf("key is pressed : * \n");
	}
	sDelay();
	if(!(*pInputDataReg & (1<<9))){
		printf("key is pressed : 0 \n");
	}
	sDelay();
	if(!(*pInputDataReg & (1<<10))){
		printf("key is pressed : # \n ");
	}
	sDelay();
	if(!(*pInputDataReg & (1<<11))){
		printf("key is pressed : D \n");
	}
	sDelay();
}


	return 0;
}

void sDelay(void){
	for(uint32_t i = 0; i<300000;i++);
}
